spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 2003739639664047
            client-secret: 245d9210d306727a330e6270fdd44c69
logging:
  level:
    org:
      springframework:
        web: debug
        security: debug